version: '3.7'
services:
    db:
        image: mysql:8.0.21
        ports:
            - ${DB_PORT}:${DB_PORT}
        expose:
            - ${DB_PORT}
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USER}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
    app:
        build: .
        restart: unless-stopped
        environment:
            DB_DATABASE: '${DB_DATABASE}'
            DB_USER: '${DB_USER}'
            DB_PASSWORD: '${DB_PASSWORD}'
            DB_PORT: ${DB_PORT}
        volumes:
            - ./:/app
        ports:
            - 3000:3000
        depends_on:
            - db
        links:
            - db:db
